apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: duckdns-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PaulCardus/doosecat
    targetRevision: HEAD
    path: environments/homelab/duckdns-cronjob
  destination:
    server: https://kubernetes.default.svc
    namespace: duck-dns-updater
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true