apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-hello-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: nginx
    targetRevision: 15.3.4
    helm:
      values: |
        image:
          repository: nginxdemos/hello
          tag: plain-text
        service:
          type: ClusterIP
          port: 80
        ingress:
          enabled: true
          hostname: hello.doosecat.duckdns.org  # Replace with your domain
          pathType: Prefix
          path: /
          ingressClassName: nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-hello-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true